import client from '@/apollo-client';
import Character from '@/components/character';
import { CharactersResponse } from '@/types';
import { gql } from '@apollo/client';
import { GetStaticProps } from 'next';
import Head from 'next/head';

type HomeProps = {
  characters: CharactersResponse;
  loading: boolean;
};

export default function Home({ characters, loading }: HomeProps) {
  // console.log(characters);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='flex flex-wrap my-4'>
        {characters?.characters?.results?.map((character) => (
          <Character
            key={character.id}
            gender={character.gender}
            image={character.image}
            location={character.location}
            name={character.name}
            status={character.status}
          />
        ))}
      </main>
    </>
  );
}

export const getStaticProps: GetStaticProps<HomeProps> = async () => {
  const { data, loading } = await client.query<CharactersResponse>({
    query: gql`
      query Characters {
        characters {
          results {
            image
            id
            location {
              name
              type
            }
            name
            status
            gender
          }
        }
      }
    `,
  });
  return {
    props: {
      characters: data,
      loading,
    },
  };
};
